# Generated by Django 3.0.5 on 2020-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_facultydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
