# Generated by Django 3.0.5 on 2020-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201031_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='permission',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
