# Generated by Django 3.0.5 on 2020-10-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201031_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='reason',
            field=models.TextField(),
        ),
    ]
